site_name: Моё портфолио
site_url: https://railmlearning.github.io/
docs_dir: source/docs
site_dir: docs
theme:
  name: dracula
nav:
  - Главная: index.md
  - Об авторе: about.md
  - Лабораторные работы: labs.md
extra_css:
  - assets/css/custom.css
