name: build-mkdocs-site

on:
  push:
    branches:
      - main  # или master, в зависимости от твоей главной ветки

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install MkDocs
        run: pip install mkdocs

      - name: Build site
        run: mkdocs build
        
      - name: Deploy to Release Branch
        run: |
          git config user.name "CI"
          git config user.email "ci@example.com"
          git fetch origin
          git checkout -B release
          # Удаляем все исходники, оставляем только сгенерированный сайт
          mv site/* .
          rm -rf site/ docs/ mkdocs.yml .sourcecraft/
          git add .
          git commit -m "Deploy site"
          git push origin release --force